### ISSUE TITLE
About extras.pak

### ISSUE THREAD

**Issue by elmemeee** [FWGS/mod-sample#1]
I know this is old but I wanted to know how the extras.pak file should look like. Do I use the same file structure as normal mods would use?

**Comment by elmemeee** [comment]
Closing it because nobody answered

**Comment by a1batross** [comment]
I thought I sent a reply here. Sorry :) 

Yeah, all PAK files use the same folder structure. They get seamlessly mounted in virtual filesystem (at least that's the idea). There is the example we bundle with the engine: https://github.com/FWGS/xash-extras

By the way, you can also use normal ZIP archives (set compression ratio to 0), just change the extension to `.pk3`.

**Comment by elmemeee** [comment]
Thanks a lot
